language: cpp
compiler: gcc
os: linux
dist: trusty
before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
install:
        - sudo apt-get install -qq g++-5
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

before_script:
        - cd ${TRAVIS_BUILD_DIR}

script:
        - make compile
        - make help